# nav.csv

In [1]:
import pandas as pd

nav = pd.read_csv('../data/raw/02_nav_history.csv')
nav.head()

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

In [2]:
nav.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  object
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ MB

In [3]:
nav['date'] =  nav['date'].astype('datetime64[ns]')

In [4]:
nav = nav.sort_values(['amfi_code','date'])
nav.head()

      amfi_code       date       nav
5750     100016 2022-01-03  520.4608
5751     100016 2022-01-04  515.0971
5752     100016 2022-01-05  521.7239
5753     100016 2022-01-06  515.7880
5754     100016 2022-01-07  515.1639

In [5]:
nav.isnull().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [6]:
nav.duplicated().sum()

np.int64(0)

In [7]:
nav[nav['nav'] <= 0]

Empty DataFrame
Columns: [amfi_code, date, nav]
Index: []

In [8]:
nav.to_csv('../data/processed/clean_nav_history.csv', index=False)

# transactions

In [9]:
tran = pd.read_csv('../data/raw/08_investor_transactions.csv')
tran.head

<bound method NDFrame.head of       investor_id transaction_date  amfi_code transaction_type  amount_inr  \
0       INV003054       2024-01-01     119092              SIP        1834
1       INV002952       2024-01-01     148567       Redemption      392882
2       INV003420       2024-01-01     118636              SIP         912
3       INV003436       2024-01-01     118634              SIP        1102
4       INV004691       2024-01-01     119094          Lumpsum        8682
...           ...              ...        ...              ...         ...
32773   INV003340       2025-05-30     101207          Lumpsum      168029
32774   INV001838       2025-05-30     119093              SIP        2175
32775   INV000074       2025-05-30     120504              SIP       25998
32776   INV002929       2025-05-30     148568              SIP         459
32777   INV001852       2025-05-30     118633       Redemption      226721

                state       city city_tier age_group  gender  \
0           Telangana  Hyderabad       T30       56+  Female
1              Punjab   Amritsar       B30     18-25    Male
2             Haryana  Faridabad       B30     36-45    Male
3         Maharashtra     Mumbai       T30     36-45  Female
4               Delhi      Noida       T30     26-35    Male
...               ...        ...       ...       ...     ...
32773  Madhya Pradesh     Indore       T30     26-35    Male
32774   Uttar Pradesh     Kanpur       B30     46-55    Male
32775       Rajasthan     Jaipur       T30     26-35  Female
32776     West Bengal    Kolkata       T30     26-35    Male
32777       Telangana  Hyderabad       T30     26-35    Male

       annual_income_lakh payment_mode kyc_status
0                    77.1          UPI   Verified
1                     7.1       Cheque   Verified
2                    47.2      Mandate   Verified
3                    54.4       Cheque    Pending
4                    14.5  Net Banking    Pending
...                   ...          ...        ...
32773                22.5  Net Banking   Verified
32774                27.6      Mandate   Verified
32775                 8.4          UPI   Verified
32776                13.0      Mandate   Verified
32777                21.7       Cheque   Verified

[32778 rows x 13 columns]>

In [10]:
print(tran['transaction_type'].unique())

['SIP' 'Redemption' 'Lumpsum']

In [11]:
tran['transaction_type'] = tran['transaction_type'].str.strip().str.upper()
tran['transaction_type'].head()

0           SIP
1    REDEMPTION
2           SIP
3           SIP
4       LUMPSUM
Name: transaction_type, dtype: object

In [12]:
tran[tran['amount_inr'] <= 0]

Empty DataFrame
Columns: [investor_id, transaction_date, amfi_code, transaction_type, amount_inr, state, city, city_tier, age_group, gender, annual_income_lakh, payment_mode, kyc_status]
Index: []

In [13]:
tran['kyc_status'].value_counts()

kyc_status
Verified    30146
Pending      2632
Name: count, dtype: int64

In [14]:
tran.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  object
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: float64(1), int64(2), object(10)
memory usage: 3.3+ MB

In [15]:
tran['transaction_date'] = tran['transaction_date'].astype('datetime64[ns]')

In [16]:
tran.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  datetime64[ns]
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(9)
memory usage: 3.3+ MB

In [25]:
tran.to_csv('../data/processed/clean_investor_transactions.csv', index=False)

# performance

In [17]:
perform = pd.read_csv('../data/raw/07_scheme_performance.csv')
perform.head()

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

In [18]:
perform.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB

In [19]:
return_cols = ["return_1yr_pct", "return_3yr_pct", "return_5yr_pct"]

for col in return_cols:
    perform[col] = pd.to_numeric(perform[col], errors="coerce")

In [20]:
for col in return_cols:
    print(f"{col} - Missing values: {perform[col].isnull().sum()}")

return_1yr_pct - Missing values: 0
return_3yr_pct - Missing values: 0
return_5yr_pct - Missing values: 0

In [21]:
perform.columns

Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='object')

In [22]:
perform[perform['sharpe_ratio'] <=0]

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [23]:
expense_ratio_flag = perform[(perform['expense_ratio_pct'] > 0.1) & (perform['expense_ratio_pct'] < 2.5)]

In [24]:
perform.to_csv('../data/processed/clean_scheme_performance.csv', index=False)

# Fund master

In [ ]:
fund  = pd.read_csv(r'../data/raw/01_fund_master.csv')
fund.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [11]:
fund.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     object
 2   scheme_name         40 non-null     object
 3   category            40 non-null     object
 4   sub_category        40 non-null     object
 5   plan                40 non-null     object
 6   launch_date         40 non-null     object
 7   benchmark           40 non-null     object
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     object
 13  risk_category       40 non-null     object
 14  sebi_category_code  40 non-null     object
dtypes: float64(2), int64(3), object(10)
memory usage: 4.8+ KB

In [12]:
fund['launch_date'] = fund['launch_date'].astype('datetime64[ns]')

In [13]:
fund.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [14]:
fund.duplicated().sum()

np.int64(0)

In [29]:
fund.to_csv('../data/processed/clean_fund_master.csv', index=False)

# AUM by fund

In [31]:
aum = pd.read_csv('../data/raw/03_aum_by_fund_house.csv')
aum.head()

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [32]:
aum.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            90 non-null     object
 1   fund_house      90 non-null     object
 2   aum_lakh_crore  90 non-null     float64
 3   aum_crore       90 non-null     int64
 4   num_schemes     90 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 3.6+ KB

In [33]:
aum['date'] = aum['date'].astype('datetime64[ns]')

In [34]:
aum.isnull().sum()

date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

In [35]:
aum.duplicated().sum()

np.int64(0)

In [37]:
aum.to_csv('../data/processed/clean_aum_by_fund_house.csv', index=False)

# sip inflow

In [39]:
sip = pd.read_csv('../data/raw/04_monthly_sip_inflows.csv')
sip.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

In [41]:
sip.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      48 non-null     object
 1   sip_inflow_crore           48 non-null     int64
 2   active_sip_accounts_crore  48 non-null     float64
 3   new_sip_accounts_lakh      48 non-null     float64
 4   sip_aum_lakh_crore         48 non-null     float64
 5   yoy_growth_pct             36 non-null     float64
dtypes: float64(4), int64(1), object(1)
memory usage: 2.4+ KB

In [44]:
sip['month'] = sip['month'].astype('datetime64[ns]').dt.month

In [47]:
sip.isnull().sum()

month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

In [48]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')
sip['yoy_growth_pct'] = imputer.fit_transform(sip[['yoy_growth_pct']])

In [50]:
sip.isnull().sum()

month                        0
sip_inflow_crore             0
active_sip_accounts_crore    0
new_sip_accounts_lakh        0
sip_aum_lakh_crore           0
yoy_growth_pct               0
dtype: int64

In [51]:
sip.duplicated().sum()

np.int64(0)

In [52]:
sip.to_csv('../data/processed/clean_monthly_sip_inflows.csv', index=False)

# category inflow

In [53]:
cat_inflow = pd.read_csv('../data/raw/05_category_inflows.csv')
cat_inflow.head()

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

In [54]:
cat_inflow.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             144 non-null    object
 1   category          144 non-null    object
 2   net_inflow_crore  144 non-null    float64
dtypes: float64(1), object(2)
memory usage: 3.5+ KB

In [55]:
cat_inflow['month'] = cat_inflow['month'].astype('datetime64[ns]').dt.month

In [56]:
cat_inflow.isnull().sum()

month               0
category            0
net_inflow_crore    0
dtype: int64

In [57]:
cat_inflow.duplicated().sum()

np.int64(0)

In [58]:
cat_inflow.to_csv('../data/processed/clean_category_inflows.csv', index=False)

# industry folio

In [60]:
indus = pd.read_csv('../data/raw/06_industry_folio_count.csv')
indus.head()

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

In [61]:
indus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                21 non-null     object
 1   total_folios_crore   21 non-null     float64
 2   equity_folios_crore  21 non-null     float64
 3   debt_folios_crore    21 non-null     float64
 4   hybrid_folios_crore  21 non-null     float64
 5   others_folios_crore  21 non-null     float64
dtypes: float64(5), object(1)
memory usage: 1.1+ KB

In [62]:
indus['month'] = indus['month'].astype('datetime64[ns]').dt.month

In [63]:
indus.duplicated().sum()

np.int64(0)

In [64]:
indus.isnull().sum()

month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

In [65]:
indus.to_csv('../data/processed/clean_industry_folio_count.csv', index=False)

# portfolio holdings

In [66]:
port = pd.read_csv(r'../data/raw/09_portfolio_holdings.csv')
port.head()

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

In [67]:
port.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   amfi_code          322 non-null    int64
 1   stock_symbol       322 non-null    object
 2   stock_name         322 non-null    object
 3   sector             322 non-null    object
 4   weight_pct         322 non-null    float64
 5   market_value_cr    322 non-null    float64
 6   current_price_inr  322 non-null    float64
 7   portfolio_date     322 non-null    object
dtypes: float64(3), int64(1), object(4)
memory usage: 20.3+ KB

In [68]:
port['portfolio_date'] = port['portfolio_date'].astype('datetime64[ns]')

In [69]:
port.duplicated().sum()

np.int64(0)

In [70]:
port.isnull().sum()

amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

In [71]:
port.to_csv('../data/processed/clean_portfolio_holdings.csv', index=False)

# benchmark indices

In [72]:
bench = pd.read_csv('../data/raw/10_benchmark_indices.csv')
bench.head()

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [73]:
bench.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8050 entries, 0 to 8049
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         8050 non-null   object
 1   index_name   8050 non-null   object
 2   close_value  8050 non-null   float64
dtypes: float64(1), object(2)
memory usage: 188.8+ KB

In [74]:
bench['date'] = bench['date'].astype('datetime64[ns]')

In [75]:
bench.duplicated().sum()

np.int64(0)

In [76]:
bench.isnull().sum()

date           0
index_name     0
close_value    0
dtype: int64

In [77]:
bench.to_csv('../data/processed/clean_benchmark_indices.csv', index=False)